apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-postgres-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-postgres-sample
  template:
    metadata:
      labels:
        app: spring-boot-postgres-sample
    spec:
      containers:
      - name: spring-boot-postgres-sample
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_host
        image: vogetisameer12/spring-boot-postgres-on-k8s-sample:latest
